---
name: Check Spotless Format Violations
on: pull_request
jobs:
  pr-spotless-check:
    name: SpotlessCheck
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654  # v5.2.0
        with:
          distribution: "temurin"
          java-package: "jdk"
          java-version: "21"
          overwrite-settings: "false"
      - name: Set up Maven
        uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1 # v5
        with:
          maven-version: 3.9.12
      - name: Maven Spotless Check
        run: >
          mvn spotless:check -Dstyle.color=always --no-transfer-progress
